<!-- Container for entire dashboard -->
<div class="container-fluid py-4">

  <!-- Dashboard header -->
  <header class="mb-4">
    <h2 class="fw-bold">Dashboard</h2>
  </header>

  <!-- Top statistics summary row -->
  <div class="row g-3">
    <div class="col-md-4">
      <div class="card shadow-sm p-3 position-relative">
        <span class="h5 fw-semibold">Total User</span>
        <div class="display-6 mt-2"><?= $totalUser ?></div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow-sm p-3 position-relative">
        <span class="h5 fw-semibold">Total Rapat</span>
        <div class="display-6 mt-2"><?= $totalRapat ?></div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card shadow-sm p-3 position-relative">
        <span class="h5 fw-semibold"><?= $levelUser?> on board </span>
        <div class="display-6 mt-2">Welcome, <?= $username ?></div>
      </div>
    </div>
  </div>


  <!-- Main dashboard content with sidebar -->
  <div class="row g-4">
    <!-- Left main content -->
    <main class="col-lg-8">
      <div class="card shadow-sm p-4 mb-4">
        <h4 class="mb-3">Statistik Transkrip</h4>
        <ul class="nav nav-tabs mb-3" id="statTabs">
          <li class="nav-item">
            <button class="nav-link active" data-range="weekly">Mingguan</button>
          </li>
          <li class="nav-item">
            <button class="nav-link" data-range="monthly">Bulanan</button>
          </li>
        </ul>
        <canvas id="transkripChart" height="400"></canvas>
      </div>
    </main>
    
    <!-- Right sidebar with calendar -->
    <aside class="col-lg-4">
      <div class="card shadow-sm p-4 mb-4">
        <h4 class="mb-3">Kalender Catatan</h4>
        <div class="calendar-container">
          <div class="calendar-header d-flex justify-content-between align-items-center mb-3">
            <button class="btn btn-sm btn-outline-secondary" id="prevMonth">
              <i class="bi bi-chevron-left"></i>
            </button>
            <h5 class="mb-0" id="currentMonth"></h5>
            <button class="btn btn-sm btn-outline-secondary" id="nextMonth">
              <i class="bi bi-chevron-right"></i>
            </button>
          </div>
          <div class="calendar-grid">
            <div class="calendar-weekdays">
              <div class="calendar-day-name">Min</div>
              <div class="calendar-day-name">Sen</div>
              <div class="calendar-day-name">Sel</div>
              <div class="calendar-day-name">Rab</div>
              <div class="calendar-day-name">Kam</div>
              <div class="calendar-day-name">Jum</div>
              <div class="calendar-day-name">Sab</div>
            </div>
            <div class="calendar-days" id="calendarDays">
              <!-- Calendar days will be generated by JavaScript -->
            </div>
          </div>
        </div>
        <div class="calendar-notes mt-3">
          <h6 class="text-muted">Catatan yang Ada</h6>
          <div id="todayNotes" class="notes-list">
            <!-- Today's notes will be displayed here -->
          </div>
        </div>
      </div>
    </aside>
  </div>
</div>

<style>
  .calendar-container {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  }

  .calendar-grid {
    border: 1px solid #dee2e6;
    border-radius: 8px;
    overflow: hidden;
  }

  .calendar-weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    background-color: #f8f9fa;
    border-bottom: 1px solid #dee2e6;
  }

  .calendar-day-name {
    padding: 8px 4px;
    text-align: center;
    font-weight: 600;
    font-size: 0.85rem;
    color: #6c757d;
    border-right: 1px solid #dee2e6;
  }

  .calendar-day-name:last-child {
    border-right: none;
  }

  .calendar-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 1px;
    background-color: #dee2e6;
  }

  .calendar-day {
    background-color: #fff;
    padding: 8px 4px;
    text-align: center;
    cursor: pointer;
    min-height: 40px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.9rem;
    position: relative;
    transition: background-color 0.2s;
  }

  .calendar-day:hover {
    background-color: #f8f9fa;
  }

  .calendar-day.today {
    background-color: #6B3A2A;
    color: white !important;
    font-weight: 600;
  }

  .calendar-day.has-notes {
    font-weight: 600;
    color: #6B3A2A;
  }

  .calendar-day.has-notes::after {
    content: '';
    position: absolute;
    bottom: 2px;
    left: 50%;
    transform: translateX(-50%);
    width: 4px;
    height: 4px;
    background-color: #6B3A2A;
    border-radius: 50%;
  }

  .calendar-day.today.has-notes::after {
    background-color: white;
  }

  .calendar-day.other-month {
    color: #adb5bd;
  }

  .notes-list {
    max-height: 200px;
    overflow-y: auto;
  }

  .note-item {
    padding: 8px;
    margin-bottom: 4px;
    background-color: #f8f9fa;
    border-radius: 4px;
    border-left: 3px solid #007bff;
  }

  .note-item h6 {
    margin: 0 0 4px 0;
    font-size: 0.9rem;
    color: #495057;
  }

  .note-item p {
    margin: 0;
    font-size: 0.8rem;
    color: #6c757d;
  }

  .note-item .note-time {
    font-size: 0.75rem;
    color: #adb5bd;
  }

  .no-notes {
    text-align: center;
    color: #adb5bd;
    font-style: italic;
    padding: 20px;
  }
</style>

<script>
  const weeklyStats = <?= json_encode($weeklyStats) ?>;
  const monthlyStats = <?= json_encode($monthlyStats) ?>;

  const ctx = document.getElementById("transkripChart").getContext("2d");

  function formatData(stats) {
    const labels = stats.map(d =>
      new Date(d.tanggal).toLocaleDateString("id-ID", { day: "numeric", month: "short" })
    );
    const values = stats.map(d => d.jumlah);
    return { labels, values };
  }

  let chartData = formatData(weeklyStats);

  let chart = new Chart(ctx, {
    type: "line",
    data: {
      labels: chartData.labels,
      datasets: [{
        label: "Jumlah Transkrip",
        data: chartData.values,
        backgroundColor: "rgba(235, 54, 54, 0.2)",
        borderColor: "rgba(211, 78, 95, 1)",
        borderWidth: 2,
        fill: true,
        tension: 0.3
      }]
    },
    options: {
      responsive: true,
      plugins: { legend: { display: false } },
      scales: { y: { beginAtZero: true, stepSize: 1 } }
    }
  });

  // Tab switching
  document.querySelectorAll("#statTabs button").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll("#statTabs button").forEach(b => b.classList.remove("active"));
      btn.classList.add("active");

      const range = btn.dataset.range;
      const stats = range === "weekly" ? weeklyStats : monthlyStats;
      const { labels, values } = formatData(stats);

      chart.data.labels = labels;
      chart.data.datasets[0].data = values;
      chart.update();
    });
  });

  // Calendar functionality
  const calendarNotes = <?= json_encode($calendarNotes) ?>;
  let currentYear = <?= $currentYear ?>;
  let currentMonth = <?= $currentMonth ?>;
  let selectedDate = new Date();

  // Initialize calendar
  function initCalendar() {
    renderCalendar(currentYear, currentMonth);
    displayTodayNotes();
  }

  // Render calendar
  function renderCalendar(year, month) {
    const firstDay = new Date(year, month - 1, 1);
    const lastDay = new Date(year, month, 0);
    const prevLastDay = new Date(year, month - 1, 0);
    const startDay = firstDay.getDay();
    const totalDays = lastDay.getDate();
    const prevTotalDays = prevLastDay.getDate();

    // Update month display
    const monthNames = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 
                       'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
    document.getElementById('currentMonth').textContent = `${monthNames[month - 1]} ${year}`;

    // Generate calendar days
    const calendarDays = document.getElementById('calendarDays');
    calendarDays.innerHTML = '';

    // Previous month days
    for (let i = startDay - 1; i >= 0; i--) {
      const day = prevTotalDays - i;
      const dayElement = createDayElement(day, true, new Date(year, month - 2, day));
      calendarDays.appendChild(dayElement);
    }

    // Current month days
    for (let day = 1; day <= totalDays; day++) {
      const date = new Date(year, month - 1, day);
      const dayElement = createDayElement(day, false, date);
      calendarDays.appendChild(dayElement);
    }

    // Next month days
    const remainingDays = 42 - (startDay + totalDays);
    for (let day = 1; day <= remainingDays; day++) {
      const dayElement = createDayElement(day, true, new Date(year, month, day));
      calendarDays.appendChild(dayElement);
    }
  }

  // Create day element
  function createDayElement(day, isOtherMonth, date) {
    const dayElement = document.createElement('div');
    dayElement.className = 'calendar-day';
    dayElement.textContent = day;

    if (isOtherMonth) {
      dayElement.classList.add('other-month');
    }

    // Check if today
    const today = new Date();
    if (date.toDateString() === today.toDateString()) {
      dayElement.classList.add('today');
    }

    // Check if has notes
    const dateString = date.toISOString().split('T')[0];
    const hasNotes = calendarNotes.some(note => note.note_date === dateString);
    if (hasNotes) {
      dayElement.classList.add('has-notes');
    }

    // Add click event
    dayElement.addEventListener('click', () => {
      selectedDate = date;
      displayNotesForDate(dateString);
    });

    return dayElement;
  }

  // Display notes for specific date
  function displayNotesForDate(dateString) {
    const notes = calendarNotes.filter(note => note.note_date === dateString);
    const todayNotesDiv = document.getElementById('todayNotes');
    
    if (notes.length === 0) {
      todayNotesDiv.innerHTML = '<div class="no-notes">Tidak ada catatan untuk tanggal ini</div>';
    } else {
      todayNotesDiv.innerHTML = notes.map(note => `
        <div class="note-item">
          <h6>${note.judul}</h6>
          <p>${note.keterangan ? note.keterangan.substring(0, 100) + '...' : 'Tidak ada keterangan'}</p>
          <div class="note-time">
            ${note.category_icon ? 
              `<i class="${note.category_icon}" style="color: ${note.category_color || '#007bff'}; margin-right: 4px;"></i>` + 
              (note.category_name || 'Tidak ada kategori') : 
              'Tidak ada kategori'
            }
          </div>
        </div>
      `).join('');
    }
  }

  // Display today's notes
  function displayTodayNotes() {
    const today = new Date().toISOString().split('T')[0];
    displayNotesForDate(today);
  }

  // Month navigation
  document.getElementById('prevMonth').addEventListener('click', () => {
    currentMonth--;
    if (currentMonth < 1) {
      currentMonth = 12;
      currentYear--;
    }
    renderCalendar(currentYear, currentMonth);
    displayTodayNotes();
  });

  document.getElementById('nextMonth').addEventListener('click', () => {
    currentMonth++;
    if (currentMonth > 12) {
      currentMonth = 1;
      currentYear++;
    }
    renderCalendar(currentYear, currentMonth);
    displayTodayNotes();
  });

  // Initialize calendar on load
  initCalendar();
</script>